# Generated by Django 3.2.9 on 2021-12-03 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'Detalle Orden', 'verbose_name_plural': 'Detalle Ordenes'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='cuantity',
            new_name='quantity',
        ),
    ]
